# Each container is its own service
# The 
services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    # Take the ./app/src folder and plug it into the container in /appcode folder
    volumes: ["./app/src:/appcode"]
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    # Take the ./api folder and plug it into the container in /appcode folder
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000

  db:
    env_file:
      - ./api/.env
    image: mysql:9
    container_name: mysql_db
    hostname: db
    # Since we are using a MySQL container (built from mysql9 image), when the
    # container is created, mysql will execute all the sql files within our
    # database-files. The "ro" at the end means copy the files such that they are
    # read-only (and executable), but not writeable
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306
